config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :leaderboards do
    resources :leaderboard_entries, only: %i[index destroy]
    post :add_score, on: :member
  end

  root to: 'leaderboards#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leaderboard.rb
class Leaderboard < ApplicationRecord
  has_many :entries, class_name: 'LeaderboardEntry'
end

app/models/leaderboard_entry.rb
# frozen_string_literal: true

class LeaderboardEntry < ApplicationRecord
  belongs_to :leaderboard

  validates :score, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/leaderboard_entries_controller.rb
# frozen_string_literal: true

class LeaderboardEntriesController < ApplicationController
  before_action :set_leaderboard_entry, only: %i[destroy]
  before_action :set_leaderboard, only: %i[index destroy]

  # GET /leaderboard_entries
  def index
    @leaderboard = Leaderboard.find(params[:leaderboard_id])
    @leaderboard_entries = LeaderboardEntry.includes(:leaderboard).where(username: params[:username])
  end

  # DELETE /leaderboard_entries/1
  def destroy
    @leaderboard_entry.destroy
    redirect_to @leaderboard, notice: 'Leaderboard entry was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_leaderboard_entry
    @leaderboard_entry = LeaderboardEntry.find(params[:id])
  end

  def set_leaderboard
    @leaderboard = Leaderboard.find(params[:leaderboard_id])
  end

  # Only allow a trusted parameter "white list" through.
  def leaderboard_entry_params
    params.require(:leaderboard_entry).permit(:leaderboard_id, :username, :score)
  end
end

app/controllers/leaderboards_controller.rb
# frozen_string_literal: true

class LeaderboardsController < ApplicationController
  before_action :set_leaderboard, only: %i[show edit update destroy add_score]

  # GET /leaderboards
  def index
    @leaderboards = Leaderboard.all
  end

  # GET /leaderboards/1
  def show
    @ranking = LeaderboardService.new(leaderboard: @leaderboard).ranking
  end

  # GET /leaderboards/new
  def new
    @leaderboard = Leaderboard.new
  end

  # GET /leaderboards/1/edit
  def edit; end

  # POST /leaderboards
  def create
    @leaderboard = Leaderboard.new(leaderboard_params)

    if @leaderboard.save
      redirect_to @leaderboard, notice: 'Leaderboard was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /leaderboards/1
  def update
    if @leaderboard.update(leaderboard_params)
      redirect_to @leaderboard, notice: 'Leaderboard was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /leaderboards/1
  def destroy
    @leaderboard.destroy
    redirect_to leaderboards_url, notice: 'Leaderboard was successfully destroyed.'
  end

  def add_score
    username = params[:username]
    score = params[:score]

    users_ranking = UsersRankingService.new(username: username, leaderboard: @leaderboard)

    if users_ranking.add_score(score)
      redirect_to @leaderboard, notice: users_ranking.position_gained_text
    else
      redirect_to @leaderboard, notice: 'Error occurred while adding scores.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_leaderboard
    @leaderboard = Leaderboard.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def leaderboard_params
    params.require(:leaderboard).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leaderboard_entries_helper.rb
module LeaderboardEntriesHelper
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leaderboards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leaderboard_entries/_form.html.erb
<%= form_with(model: leaderboard_entry, local: true) do |form| %>
  <% if leaderboard_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leaderboard_entry.errors.count, "error") %> prohibited this leaderboard_entry from being saved:</h2>

      <ul>
      <% leaderboard_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :leaderboard_id %>
    <%= form.text_field :leaderboard_id, id: :leaderboard_entry_leaderboard_id %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :leaderboard_entry_username %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score, id: :leaderboard_entry_score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leaderboard_entries/edit.html.erb
<h1>Editing Leaderboard Entry</h1>

<%= render 'form', leaderboard_entry: @leaderboard_entry %>

<%= link_to 'Show', @leaderboard_entry %> |
<%= link_to 'Back', leaderboard_entries_path %>

app/views/leaderboard_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leaderboard Entries</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leaderboard_entries.each do |leaderboard_entry| %>
      <tr>
        <td><%= leaderboard_entry.username %></td>
        <td><%= leaderboard_entry.score %></td>
        <td><%= link_to 'Destroy', [@leaderboard, leaderboard_entry], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Scores', @leaderboard %>

app/views/leaderboard_entries/new.html.erb
<h1>New Leaderboard Entry</h1>

<%= render 'form', leaderboard_entry: @leaderboard_entry %>

<%= link_to 'Back', leaderboard_entries_path %>

app/views/leaderboard_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Leaderboard:</strong>
  <%= @leaderboard_entry.leaderboard %>
</p>

<p>
  <strong>Username:</strong>
  <%= @leaderboard_entry.username %>
</p>

<p>
  <strong>Score:</strong>
  <%= @leaderboard_entry.score %>
</p>

<%= link_to 'Edit', edit_leaderboard_entry_path(@leaderboard_entry) %> |
<%= link_to 'Back', leaderboard_entries_path %>

app/views/leaderboards/_form.html.erb
<%= form_with(model: leaderboard, local: true) do |form| %>
  <% if leaderboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leaderboard.errors.count, "error") %> prohibited this leaderboard from being saved:</h2>

      <ul>
      <% leaderboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :leaderboard_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leaderboards/edit.html.erb
<h1>Editing Leaderboard</h1>

<%= render 'form', leaderboard: @leaderboard %>

<%= link_to 'Show', @leaderboard %> |
<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leaderboards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leaderboards.each do |leaderboard| %>
      <tr>
        <td><%= leaderboard.name %></td>
        <td><%= link_to 'Show', leaderboard %></td>
        <td><%= link_to 'Edit', edit_leaderboard_path(leaderboard) %></td>
        <td><%= link_to 'Destroy', leaderboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leaderboard', new_leaderboard_path %>

app/views/leaderboards/new.html.erb
<h1>New Leaderboard</h1>

<%= render 'form', leaderboard: @leaderboard %>

<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @leaderboard.name %>
</p>

<div>
  <p>Ranking:</p>
  <ol>
    <% @ranking.each do |username, score| %>
      <li>
        <%= link_to username, leaderboard_leaderboard_entries_path(@leaderboard, username: username) %> - 
        <%= score %>
      </li>
    <% end -%>
  </ol>
</div>

<div>
  <%= form_tag add_score_leaderboard_path(@leaderboard), method: :post do %>
    <p>
      <%= label_tag "Username" %>
      <%= text_field_tag "username" %>
    </p>
    <p>
      <%= label_tag "Score" %>
      <%= text_field_tag "score" %>
    </p>
    <%= submit_tag "Add score" %>
  <% end -%>
</div>

<hr>

<%= link_to 'Edit', edit_leaderboard_path(@leaderboard) %> |
<%= link_to 'Back', leaderboards_path %>